baseURL = '/'
languageCode = 'en-us'
title = 'Hitesh Pattanayak'
theme = "gohugo-theme-ananke"

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 15

[params]
github = "https://github.com/HiteshRepo"
linkedin = "https://www.linkedin.com/in/hitesh-pattanayak/"
show_reading_time = false
recent_posts_number = 0
site_logo = "HP"
