baseURL = 'https://hitesh-pattanayak.netlify.app/'
languageCode = 'en-us'
title = 'Hitesh Pattanayak'
author = 'Hitesh Pattanayak'
theme = "gohugo-theme-ananke"

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 15

[params]
pagetitle = "Portfolio"
copyright = "Â© 2024-2026"
copyrightUrl = "https://hitesh-pattanayak.netlify.app/"
faviconfile = "image/favicon.png"
logofile = "image/avatar.png"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false
github = "https://github.com/HiteshRepo"
linkedin = "https://www.linkedin.com/in/hitesh-pattanayak/"
custom_css = ["styles/design-system.css"]
recent_posts_number = 0
site_logo = "HP"

googleAnalytics ='G-SSRQWT3E10'